//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComPairSE.FirstService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FirstService.IDataService")]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/CreateReceipt", ReplyAction="http://tempuri.org/IDataService/CreateReceiptResponse")]
        string CreateReceipt(string receiptData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/CreateReceipt", ReplyAction="http://tempuri.org/IDataService/CreateReceiptResponse")]
        System.Threading.Tasks.Task<string> CreateReceiptAsync(string receiptData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/getAllReceiptsFromHistory", ReplyAction="http://tempuri.org/IDataService/getAllReceiptsFromHistoryResponse")]
        string getAllReceiptsFromHistory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/getAllReceiptsFromHistory", ReplyAction="http://tempuri.org/IDataService/getAllReceiptsFromHistoryResponse")]
        System.Threading.Tasks.Task<string> getAllReceiptsFromHistoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/LoadDataFromFile", ReplyAction="http://tempuri.org/IDataService/LoadDataFromFileResponse")]
        void LoadDataFromFile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/LoadDataFromFile", ReplyAction="http://tempuri.org/IDataService/LoadDataFromFileResponse")]
        System.Threading.Tasks.Task LoadDataFromFileAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/SaveDataToFile", ReplyAction="http://tempuri.org/IDataService/SaveDataToFileResponse")]
        void SaveDataToFile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/SaveDataToFile", ReplyAction="http://tempuri.org/IDataService/SaveDataToFileResponse")]
        System.Threading.Tasks.Task SaveDataToFileAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetReceiptByID", ReplyAction="http://tempuri.org/IDataService/GetReceiptByIDResponse")]
        string GetReceiptByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetReceiptByID", ReplyAction="http://tempuri.org/IDataService/GetReceiptByIDResponse")]
        System.Threading.Tasks.Task<string> GetReceiptByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetReceiptsByDate", ReplyAction="http://tempuri.org/IDataService/GetReceiptsByDateResponse")]
        string GetReceiptsByDate(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetReceiptsByDate", ReplyAction="http://tempuri.org/IDataService/GetReceiptsByDateResponse")]
        System.Threading.Tasks.Task<string> GetReceiptsByDateAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : ComPairSE.FirstService.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<ComPairSE.FirstService.IDataService>, ComPairSE.FirstService.IDataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CreateReceipt(string receiptData) {
            return base.Channel.CreateReceipt(receiptData);
        }
        
        public System.Threading.Tasks.Task<string> CreateReceiptAsync(string receiptData) {
            return base.Channel.CreateReceiptAsync(receiptData);
        }
        
        public string getAllReceiptsFromHistory() {
            return base.Channel.getAllReceiptsFromHistory();
        }
        
        public System.Threading.Tasks.Task<string> getAllReceiptsFromHistoryAsync() {
            return base.Channel.getAllReceiptsFromHistoryAsync();
        }
        
        public void LoadDataFromFile() {
            base.Channel.LoadDataFromFile();
        }
        
        public System.Threading.Tasks.Task LoadDataFromFileAsync() {
            return base.Channel.LoadDataFromFileAsync();
        }
        
        public void SaveDataToFile() {
            base.Channel.SaveDataToFile();
        }
        
        public System.Threading.Tasks.Task SaveDataToFileAsync() {
            return base.Channel.SaveDataToFileAsync();
        }
        
        public string GetReceiptByID(int id) {
            return base.Channel.GetReceiptByID(id);
        }
        
        public System.Threading.Tasks.Task<string> GetReceiptByIDAsync(int id) {
            return base.Channel.GetReceiptByIDAsync(id);
        }
        
        public string GetReceiptsByDate(System.DateTime date) {
            return base.Channel.GetReceiptsByDate(date);
        }
        
        public System.Threading.Tasks.Task<string> GetReceiptsByDateAsync(System.DateTime date) {
            return base.Channel.GetReceiptsByDateAsync(date);
        }
    }
}
