//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComPairSE.FirstService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FirstService.IDataService")]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Test", ReplyAction="http://tempuri.org/IDataService/TestResponse")]
        string Test(string hey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Test", ReplyAction="http://tempuri.org/IDataService/TestResponse")]
        System.Threading.Tasks.Task<string> TestAsync(string hey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/CreateReceipt", ReplyAction="http://tempuri.org/IDataService/CreateReceiptResponse")]
        string[] CreateReceipt(string receiptData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/CreateReceipt", ReplyAction="http://tempuri.org/IDataService/CreateReceiptResponse")]
        System.Threading.Tasks.Task<string[]> CreateReceiptAsync(string receiptData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : ComPairSE.FirstService.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<ComPairSE.FirstService.IDataService>, ComPairSE.FirstService.IDataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Test(string hey) {
            return base.Channel.Test(hey);
        }
        
        public System.Threading.Tasks.Task<string> TestAsync(string hey) {
            return base.Channel.TestAsync(hey);
        }
        
        public string[] CreateReceipt(string receiptData) {
            return base.Channel.CreateReceipt(receiptData);
        }
        
        public System.Threading.Tasks.Task<string[]> CreateReceiptAsync(string receiptData) {
            return base.Channel.CreateReceiptAsync(receiptData);
        }
    }
}
